import { expect, test } from "vitest";
import { GamePhase, State, createInitialState } from "./state";

test("createInitialState", () => {
  expect(createInitialState(0)).toEqual<State>({
    deck: [
      "AS",
      "TC",
      "9D",
      "2S",
      "TH",
      "KC",
      "JC",
      "5S",
      "3H",
      "8S",
      "4C",
      "4D",
      "3S",
      "JS",
      "JD",
      "QD",
      "2H",
      "5C",
      "KS",
      "7D",
      "JH",
      "3D",
      "AH",
      "QS",
      "6D",
      "9H",
      "KD",
      "AC",
      "6C",
      "7C",
      "TD",
      "2C",
      "6H",
    ],
    player1Hand: ["4H", "9S", "QH", "TS", "7H", "5D", "AD", "8H", "3C"],
    player2Hand: ["9C", "4S", "7S", "5H", "QC", "8D", "6S", "8C", "2D"],
    melds: [],
    discard: ["KH"],
    player1First: true,
    player1Turn: true,
    phase: GamePhase.DRAW,
    player1Score: 0,
    player2Score: 0,
  });
});
